// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentKind {
    Spirit,
    Mind,
    Criome,
    Message,
    Router,
    Mirror,
    Terminal,
    Harness,
    Agent,
    System,
    Introspect,
    Orchestrate,
    Lojix,
    Persona,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AuthorizedObjectKind {
    Operation,
    Contract,
    Agreement,
    Time,
    Head,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Differentiator {
    pub component_kind: ComponentKind,
    pub authorized_object_kind: AuthorizedObjectKind,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentObjectInterest {
    pub component_kind: ComponentKind,
    pub authorized_object_kind: AuthorizedObjectKind,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AuthorizedObjectInterest {
    AnyAuthorizedObject,
    Component(ComponentKind),
    ObjectKind(AuthorizedObjectKind),
    ComponentObject(ComponentObjectInterest),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObjectDigest(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketPath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NetworkPort(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NetworkEndpoint {
    pub host_name: HostName,
    pub network_port: NetworkPort,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum StandardSocket {
    UnixSocket(SocketPath),
    NetworkSocket(NetworkEndpoint),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizedObjectReference {
    pub component_kind: ComponentKind,
    pub object_digest: ObjectDigest,
    pub authorized_object_kind: AuthorizedObjectKind,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentClassification {
    pub differentiator: Differentiator,
    pub authorized_object_interest: AuthorizedObjectInterest,
}

#[rustfmt::skip]
impl ObjectDigest {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ObjectDigest {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SocketPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HostName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HostName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NetworkPort {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for NetworkPort {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizedObjectInterest {
    pub fn component(payload: ComponentKind) -> Self {
        Self::Component(payload)
    }
    pub fn object_kind(payload: AuthorizedObjectKind) -> Self {
        Self::ObjectKind(payload)
    }
    pub fn component_object(payload: ComponentObjectInterest) -> Self {
        Self::ComponentObject(payload)
    }
}

#[rustfmt::skip]
impl StandardSocket {
    pub fn unix_socket(payload: String) -> Self {
        Self::UnixSocket(SocketPath::new(payload))
    }
    pub fn network_socket(payload: NetworkEndpoint) -> Self {
        Self::NetworkSocket(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentKind> for AuthorizedObjectInterest {
    fn from(payload: ComponentKind) -> Self {
        Self::Component(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizedObjectKind> for AuthorizedObjectInterest {
    fn from(payload: AuthorizedObjectKind) -> Self {
        Self::ObjectKind(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentObjectInterest> for AuthorizedObjectInterest {
    fn from(payload: ComponentObjectInterest) -> Self {
        Self::ComponentObject(payload)
    }
}

#[rustfmt::skip]
impl From<SocketPath> for StandardSocket {
    fn from(payload: SocketPath) -> Self {
        Self::UnixSocket(payload)
    }
}

#[rustfmt::skip]
impl From<NetworkEndpoint> for StandardSocket {
    fn from(payload: NetworkEndpoint) -> Self {
        Self::NetworkSocket(payload)
    }
}
