// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentKind {
    Spirit,
    Mind,
    Criome,
    Message,
    Router,
    Mirror,
    Terminal,
    Harness,
    Agent,
    System,
    Introspect,
    Orchestrate,
    Lojix,
    Persona,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AuthorizedObjectKind {
    Operation,
    Contract,
    Agreement,
    Time,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Differentiator {
    pub component: ComponentKind,
    pub kind: AuthorizedObjectKind,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentObjectInterest {
    pub component: ComponentKind,
    pub kind: AuthorizedObjectKind,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AuthorizedObjectInterest {
    AnyAuthorizedObject,
    Component(ComponentKind),
    ObjectKind(AuthorizedObjectKind),
    ComponentObject(ComponentObjectInterest),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObjectDigest(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizedObjectReference {
    pub component: ComponentKind,
    pub digest: ObjectDigest,
    pub kind: AuthorizedObjectKind,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentClassification {
    pub differentiator: Differentiator,
    pub advertises: AuthorizedObjectInterest,
}

#[rustfmt::skip]
impl ObjectDigest {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ObjectDigest {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AuthorizedObjectInterest {
    pub fn component(payload: ComponentKind) -> Self {
        Self::Component(payload)
    }
    pub fn object_kind(payload: AuthorizedObjectKind) -> Self {
        Self::ObjectKind(payload)
    }
    pub fn component_object(payload: ComponentObjectInterest) -> Self {
        Self::ComponentObject(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentKind> for AuthorizedObjectInterest {
    fn from(payload: ComponentKind) -> Self {
        Self::Component(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizedObjectKind> for AuthorizedObjectInterest {
    fn from(payload: AuthorizedObjectKind) -> Self {
        Self::ObjectKind(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentObjectInterest> for AuthorizedObjectInterest {
    fn from(payload: ComponentObjectInterest) -> Self {
        Self::ComponentObject(payload)
    }
}
